apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Root Channel and Subscription to maintain ACM policies


namespace: demo-mcm-policies

resources:
- namespace.yaml
- rbac.yaml
- channel.yaml
- placement.yaml
- sub.yaml
#- app.yaml