---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: gitops/subs-managed/policies
  labels:
    app: mcm-policy
  name: mcm-policy-root-sub
  namespace: demo-mcm-policies
spec:
  channel: demo-mcm-policies/mcm-policy-root-chan
  placement:
#    local: true
    placementRef:
      kind: PlacementRule
      name: mcm-policy-placement